---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "10.0.54.32"}]
  synced_folders:
    - [".", "/home/vagrant/epgsql", "create: true"]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[epgsql]
    attributes: { postgresql: {version: "9.3"}}
